version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app-backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - minio
    volumes:
      - media_tmp:/app/tmp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 20s
      timeout: 5s
      retries: 5

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app-worker
    command: bash -lc "celery -A app.tasks.celery_app.celery_app worker --loglevel=INFO"
    env_file: .env
    depends_on:
      - backend
      - redis
      - postgres
    volumes:
      - media_tmp:/app/tmp

  beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app-beat
    command: bash -lc "celery -A app.tasks.celery_app.celery_app beat --loglevel=INFO"
    env_file: .env
    depends_on:
      - worker
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  postgres:
    image: postgres:15
    container_name: app-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: app-redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2024-01-11T07-46-16Z
    container_name: app-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  createbuckets:
    image: minio/mc:RELEASE.2024-01-11T03-31-17Z
    container_name: app-minio-mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      mc mb -p local/${S3_BUCKET} || true &&
      mc anonymous set download local/${S3_BUCKET} || true &&
      sleep 2
      "

volumes:
  pgdata:
  media_tmp:
  minio_data:

networks:
  default:
    name: appnet
